version: '3.9'

services:

  web:
    depends_on: 
      - wordpress
    build: ./docker-config/apache
    image: myproject_apache
    container_name: myproject_apache
    ports:
      - "81:80"
      - "443:443"
    volumes: 
      - ./www:/var/www/html
      - ./docker-config/apache/sites-enabled:/etc/apache2/sites-enabled
    networks: 
      - myproject_net

  wordpress:
    depends_on:
      - db
    build: ./docker-config/wordpress
    image: myproject_wordpress
    container_name: myproject_wordpress
    env_file: ./.env
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: $MYSQL_USER
      WORDPRESS_DB_PASSWORD: $MYSQL_PASSWORD
      WORDPRESS_DB_NAME: $MYSQL_DATABASE
    volumes:
      - ./www:/var/www/html
    networks:
      - myproject_net

  db:
    image: mysql:5.7
    container_name: myproject_db
    env_file: ./.env
    # environment:
    #   MYSQL_ROOT_PASSWORD: root
    #   MYSQL_DATABASE: exampledb
    #   MYSQL_USER: exampleuser
    #   MYSQL_PASSWORD: examplepass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - myproject_net
  
  phpmyadmin:
    depends_on: 
      - db
    image: phpmyadmin
    container_name: myproject_phpmyadmin
    ports:
      - "82:80"
    environment: 
      - PMA_ARBITRARY=1
    networks: 
      - myproject_net

volumes:
  db_data:
networks:
  myproject_net: